# These are supported funding model platforms

github: rikimaru0345
custom: https://www.paypal.me/rikimaru0345
ko_fi: rikimaru


patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
